#!/bin/bash

source_dir=$(pwd)

dest_dir=$(dirname "$source_dir")

find "$source_dir" -maxdepth 1 -type f -name "*.html" | while read -r html_file; do
    filename=$(basename "$html_file")

    if [ -e "$dest_dir/filename" ]; then
        if ["$html_file" -nt "$dest_dir/$filename" ]
            cp "$html_file" "$dest_dir/$filename"
            echo "Copied '$filname' to '$dest_dir/$filename'"
        fi
     else
        cp "$html_file" "$dest_dir/$filename"
        echo "Copied '$filename' to '$dest_dir/$filname'"

        fi
  done 
